server:
  port: 8188
  servlet:
    context-path: /winter-market-auth
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./wmusers;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      setting:
        web-allow-others: false
jwt:
  secret: 1234567890
  lifetime: 36000000

