server:
  port: 8189
  servlet:
    context-path: /winter-market-core
spring:
  datasource:
    url: jdbc:h2:mem:wmcore;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      setting:
        web-allow-others: false
integrations:
  cart-service:
    url: http://localhost:8190/winter-market-carts/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000

